config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  get("/users/:id/change_password", to: "users#change_password")
  patch("/users/:id", to: "users#update", as: :new_password)
  resources :users, only: [:new, :create, :edit, :update]

  resource :session, only: [:new,:create, :destroy]

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end


end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end

    if user.is_admin?
      can :manage, :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    alias_action :create, :read, :update, :destroy, to: :crud 

    can(:crud, Post) do |post| 
      post.user == user 
    end

    can(:crud, Comment) do |comment| 
      comment.user == user || comment.post.user == user
    end

    can(:crud, User) do |user_logged|
      user_logged == user
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :body, presence: { message: "must exist" }
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    

    validates :title, presence: true, uniqueness: {case_sensitive: false}
    validates :body, presence: { message: "must exist" },length: { minimum: 50 }
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :email, uniqueness:true, format: {with: URI::MailTo::EMAIL_REGEXP}
    
    has_many :posts
    has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
    
    def current_user
        if session[:user_id].present?
          @current_user ||= User.find session[:user_id] 
        end
    end

    helper_method :current_user
   
    def user_signed_in?
        current_user.present?
    end

    helper_method :user_signed_in?

    def authenticate_user!
        unless user_signed_in?
          flash[:danger] = "You need to be signed in first!"
          redirect_to root_path
        end
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
        @post = Post.find params[:post_id]
        comment_params = params.require(:comment).permit(:body)
        @comment = Comment.new comment_params
        @comment.user = @current_user
        @comment.post = @post
        @comment.save
        redirect_to post_path(@post), notice: 'Comment created!'
    end

    def destroy
        @comment = Comment.find params[:id]
        if can?(:crud, @comment)
            @comment.destroy 
            redirect_to post_path(@comment.post)
        else
            #head :unauthorized
            flash[:warning] = "You do not have permition to make this action"    
            redirect_to post_path(@comment.post)
        end
    end

    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :authorize!, only: [:edit, :update, :destroy]
    
    def index
        @posts = Post.all.order(created_at: :desc)
    end 

    def show
        @post = Post.find(params[:id])
        @comment = Comment.new
        @comments = @post.comments.order(created_at: :desc)
    end 

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(params.require(:post).permit(:title, :body, :image)) 
        @post.user = @current_user
        if @post.save  
            redirect_to posts_path  
        else 
            render :new 
	    end
    end 

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end

    def edit
        @post = Post.find(params[:id])
    end 

    def update 
        @post = Post.find(params[:id])
        if @post.update(params.require(:post).permit(:title, :body, :image))
            redirect_to post_path(@post) 
        else 
            render :edit
	    end
    end

    private

    def authorize! 
        @post= Post.find(params[:id])
        redirect_to root_path, alert: 'Not Authorized' unless can?(:crud, @post)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end 

    def create

        user = User.find_by_email params[:email]
        if user&.authenticate params[:password]
          session[:user_id] = user.id
          redirect_to root_path
        else
          flash[:danger] = "The username and password combination is not recognized. Please try again."
          render :new
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize!, only: [:edit, :update, :change_password]
  
  def new
      @user = User.new
  end

  def create

    @user = User.new params.require(:user).permit(:name, :email, :password, :password_confirmation)
      if @user.save  
          redirect_to root_path 
      else
          flash[:warning] = "Unable to create user,please try again" 
          render :new 
	  end
  end

  def edit
     @user = User.find(params[:id])# @user User.find session[:user_id]
     # # the current_user method already fetches the logged in user for us
    end

  def update
  
      @user = User.find params[:id]
      if (current_user.authenticate(params[:user][:current_password]))
          if params[:user][:current_password]!= params[:user][:password] && params[:user][:password] == params[:user][:password_confirmation] 
                @user.update(params.require(:user).permit(:password, :password_confirmation))
                redirect_to root_path
          end
      elsif @user.update(params.require(:user).permit(:name, :email))
          redirect_to root_path
      else
          flash[:warning] = "Unable to change password" 
          render :change_password  
      end
     
      
  end

  def change_password
    @user = User.find(params[:id])
  end

  private

    def authorize! 
        @user= User.find(params[:id])
        redirect_to root_path, alert: 'Not Authorized' unless can?(:crud, @user)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogOnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
  <div class="container">
    <% flash.each do |type, message| %>
          <div class='bg-<%= type %> p-3 rounded mb-2 shadow-sm'>
            <%= message %>
          </div>
    <% end %>
    <%= yield %>
  </div>  
  </body>
</html>

app/views/posts/edit.html.erb
<br>
<div class="container-float">
    <% if @post.errors.present? %>
    <p class="text-danger">
        <%= @post.errors.full_messages.join(', ')%>
    </p>
    <% end %>
    <%= form_with(model: @post, local: true) do |form| %>
        <div class="form-group " >
        <%= form.label :title %> <br>
        <%= form.text_field(:title, class: "form-control" ) %>
        </div>
        <div class="form-group" >
        <%= form.label :body %> <br>
        <%= form.text_area :body, cols: 50, rows: 5, class: "form-control"  %>
        </div>
        <%= form.submit "Update Post", class: "btn btn-outline-primary"  %>
   
    <% end %>
</div>

app/views/posts/index.html.erb
<div class="row" >
        <% @posts.each do |post| %>
            <div class=" col-sm-4">
                <div class="card-deck mb-3 ">        
                <div class="card w-100">
                    <div class="card-body">
                        <a href="/posts/<%=post.id%>">
                        <h5 class="card-title text-nowrap text-truncate"><%=post.title%></h5>
                        </a>
                        <p class="card-text text-nowrap text-truncate"><%=post.body%></p>
                    </div>
                </div>
                </div>       
            </div>
        <% end %>
</div>

app/views/posts/new.html.erb
<br>
<div class="container-float">
    <% if @post.errors.present? %>
    <p class="text-danger">
        <%= @post.errors.full_messages.join(', ')%>
    </p>
    <% end %>
    <%= form_with(model: @post, local: true) do |form| %>
    <div>
        <div class="form-group " >
            <%= form.label :title %> <br>
            <%= form.text_field(:title, class: "form-control" ) %>
        </div>
        <div class="form-group" >
            <%= form.label :body %> <br>
            <%= form.text_area :body, cols: 50, rows: 5, class: "form-control"  %>
        </div>
        <%= form.submit "Create Post", class: "btn btn-outline-primary" %>
    </div>
    <% end %>
</div>

app/views/posts/show.html.erb
<br>
<div class="container-float">
    <h1 class="font-weight-bold"><%= @post.title %></h1>
    <p class="text-justify"><%= @post.body%></p>
    <div>
        <small>Posted <%= time_ago_in_words(@post.created_at)%> ago.</small> 
    </div>
<br>
    <div> 
        <%= link_to(
        "Edit",
        edit_post_path(@post),
        class: 'btn btn-outline-primary'
        )
        %>
        <%= link_to(
        "Delete",
        post_path(@post),
        method: :delete,
        class: 'btn btn-outline-primary',
        data: { confirm: 'Are you sure you want to delete this post?' }
        )
        %>
    </div>
<br>
    <div class=" rounded">
        <%= simple_form_for [@post, @comment] do |f| %>
       <h5> <%= f.input :body, label: "Comment", class: "format-group", placeholder: "What's on your mind?" %> </h5>
        <%= f.submit "Submit", class: "btn btn-outline-primary"%>
        <% end %>
    </div>
<br>
    <div class="container-float ">
        <% @comments.each do |comment| %>
            <div >
               <div class="font-weight-bold"><%=comment.user.name%> </div>
             <%= comment.body %> <br>
                <div class=" d-flex  align-items-center w-100">
                    <small >
                    Commented <%= time_ago_in_words(comment.created_at) %> ago •
                    </small>
                    <small >
                    <%= link_to(
                        "Delete",
                        post_comment_path(@post, comment),
                        method: :delete, 
                        data: {
                        confirm: "Are you sure?"
                        },
                        class: 'btn btn-link text-primary ',
                    ) %>
                    </small> 
                    
                </div>
                <br>
            </div>    
        <% end %>
    </ul>
</div> 

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand navbar-dark bg-light">
  <h4 class="navbar-brand text-primary" >Blog On Rails</h4>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExample02">
    <ul class="navbar-nav mr-auto"></ul>
    <div class="my-2 my-md-0">
      <a class="p-2 text-primary" href="/">Home</a>
      <a class="p-2 text-primary" href="/posts/new">New Posts</a>
        <% if user_signed_in? %>
            <%= link_to "Logout", session_path, method: :delete, class:'btn btn-danger btn-sm' %>
            <a class="p-2 text-primary font-weight-bold " href="/users/<%=current_user.id%>/edit"><%= current_user.name %> </a>
          <% else  %>
            <%= link_to "Log In", new_session_path, class: 'btn btn-outline-primary '%>
            <a class="p-2 btn btn-primary" href="/users/new">Sign Up</a>
        <% end %>
    </div>
  </div>
</nav>
<br>

app/views/users/change_password.html.erb
<div class='container'>
    <% if @user.errors.present? %>
    <%byebug%>
        <p class="text-danger">
            <%= @user.errors.full_messages.join(', ')%>
        </p>
    <% end %>
    <%= form_with(model: @user, local: true) do |form| %>
        <div class='shadow-none p-3 mb-5 bg-light rounded'>
            <div class="form-group" >
                <%= form.label :current_password %> <br>
                <%= form.password_field :current_password, class: "form-control"  %>
            </div>
            <div class="form-group">
                <%= form.label :new_Password %>
                <%= form.password_field :password, class: "form-control"  %>
            </div>
            <div class="form-group">
                <%= form.label :new_password_confirmation %>
                <%= form.password_field :password_confirmation, class: "form-control"  %>
            </div>
            <%= form.submit "Submit", class: "btn btn-info" %>
        </div>
<% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
<h1 class="p-3 mb-2 " >Edit Profile</h1>
  <% if @user.errors.present? %>
    <p class="text-danger">
        <%= @user.errors.full_messages.join(', ')%>
    </p>
    <% end %>
  
<%= form_with(model: @user, local: true) do |form| %>
  <div class='shadow-none p-3 mb-5 bg-light rounded'>
    <div class="form-group " >
      <%= form.label :name %> <br>
      <%= form.text_field(:name, class: "form-control" ) %>
    </div>
    <div class="form-group" >
      <%= form.label :email %> <br>
      <%= form.text_field :email, class: "form-control"  %>
    </div>
    <%= form.submit "Submit", class: "btn btn-info" %>
    <a type="button" class="btn btn-primary" href="/users/<%=@user.id%>/change_password">Change Password</a>
  </div>
<% end %>

</div>

app/views/users/new.html.erb
<div class='container'>
<%= form_with(model: @user, local: true) do |form| %>
  <div class='shadow-none p-3 mb-5 bg-light rounded'>
    <div class="form-group " >
      <%= form.label :name %> <br>
      <%= form.text_field(:name, class: "form-control" )%>
    </div>
    <div class="form-group" >
      <%= form.label :email %> <br>
      <%= form.text_field :email, class: "form-control"  %>
    </div>
    <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control"  %>
    </div>
    <div class="form-group">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "form-control"  %>
    </div>
    <%= form.submit "Submit", class: "btn btn-info" %>
  </div>
<% end %>
</div>